language: node_js
node_js: node
before_install:
- npm install -g typescript
script:
- npm run test
- npm run build
cache:
  directories:
  - node_modules
deploy:
  provider: s3
  access_key_id: AKIAJUVSS3ZQNE55X64Q
  secret_access_key:
    secure: YjCgpOOly+mi7QHnlrFymR21z9YJpRqK96f+5O8t42ZQ5YEV8BONyM8QZ6lAd8uuuHno8a7xBqDV9bSh1W8Ega3kS4Tj9UEKitMlwG0lO3TrMYNpdvgHVLgYZs2oYVIgu0ow1A2vs0MDKEWXOJBzKLVaLpZzueYTHAf+nMCm6+WcH5rP4Gnslgs6Xp8qRfCead7a5PYSv78mkr+uHzq2ELzdVk2w3v+IDhSdOplfK4gQlRmkQvuyyq1cGOmyuYwaNsjSslhBa3iBTkFkv8ldcGjKGeBDzfCXJ3y3aKqqAY1xrTWUhRRkvH5huRh4+Gn2BOlL1cXBGyOEkG/KOxJxuPp1+hQid7vmBm0CJ4qLbjb0j4bM7F0la+JtPSDU9bsduJ769N+8LoQcV7GJJre6CPTjnK1mxcIYyvmPEmSYNjnLVh9W/q9Tux6pP8MlBufUiNdcFMQzKI92+KOtrGREZn7BD6VvRAcga10Eame3hwChbGQVeq/p5C+epgmr1dyhBMoxQaOr4OYHC5sjdd4bhK+7LBONWyiTtoFKF40r/OxTQgg+4MhbNtW7OON2B81V1tESKMqzvjMzrvq4ANu19f6dTebd8iHNVkNU/k8NmA3TAnqtD1A1ljTcUyZRC6JyIczq/MznWLlBde3Q21GXkd7MYK3igdXh5oMr40LNa44=
  bucket: aws-website-cardinal-ng-y2tww
  local-dir: dist
  acl: public_read
  skip_cleanup: true
  on:
    repo: mpiroc/cardinal-ng
    branch: staging
